python3 tests/agent_test.py oneplus 1 "open settings" "open wifi settings page" "open display settings"
python3 tests/agent_test.py oneplus 2 "turn up the volume once" "open https://www.bing.com" "open wechat"
python3 tests/agent_test.py oneplus 3 "open douyin and scroll down once" "open bluetooth settings page" "open settings"
python3 tests/agent_test.py oneplus 4 "open wifi settings page" "open display settings" "turn up the volume once"
python3 tests/agent_test.py oneplus 5 "open https://www.bing.com" "open wechat" "open douyin and scroll down once"
python3 tests/agent_test.py oneplus 6 "open bluetooth settings page" "open settings" "open wifi settings page"
python3 tests/agent_test.py oneplus 7 "open display settings" "turn up the volume once" "open https://www.bing.com"
python3 tests/agent_test.py oneplus 8 "open wechat" "open douyin and scroll down once" "open bluetooth settings page"
python3 tests/agent_test.py oneplus 9 "open settings" "open wifi settings page" "open display settings"
python3 tests/agent_test.py oneplus 10 "turn up the volume once" "open https://www.bing.com" "open wechat"
