python3 tests/agent_test.py tablet 1 "open settings" "open wifi settings page" "open display settings"
python3 tests/agent_test.py tablet 2 "turn up the volume once" "open https://www.bing.com" "open taobao and scroll down once"
python3 tests/agent_test.py tablet 3 "open com.xingin.xhs and scroll down once" "open bluetooth settings page" "open settings"
python3 tests/agent_test.py tablet 4 "open wifi settings page" "open display settings" "turn up the volume once"
python3 tests/agent_test.py tablet 5 "open https://www.bing.com" "open taobao and scroll down once" "open com.xingin.xhs and scroll down once"
python3 tests/agent_test.py tablet 6 "open bluetooth settings page" "open settings" "open wifi settings page"
python3 tests/agent_test.py tablet 7 "open display settings" "turn up the volume once" "open https://www.bing.com"
python3 tests/agent_test.py tablet 8 "open taobao and scroll down once" "open com.xingin.xhs and scroll down once" "open bluetooth settings page"
python3 tests/agent_test.py tablet 9 "open settings" "open wifi settings page" "open display settings"
python3 tests/agent_test.py tablet 10 "turn up the volume once" "open https://www.bing.com" "open taobao and scroll down once"
